### ISSUE TITLE
Неточно определяет часовой пояс

### ISSUE THREAD

**Issue by krotesk** [spider863644/PhoneNumber-OSINT#1]
Ну как неточно - похоже перечисляются всевозможные часовые пояса для номера.
```
Getting basic informations from +792262.....
Parsed Phone Number is :  Country Code: 7 National Number: 92262.....
Region of Phone Number is:  Russia
Time Zone of the number is :  ('Asia/Almaty', 'Asia/Anadyr', 'Asia/Aqtobe', 'Asia/Irkutsk', 'Asia/Kamchatka', 'Asia/Krasnoyarsk', 'Asia/Magadan', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Sakhalin', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yekaterinburg', 'Europe/Bucharest', 'Europe/Moscow', 'Europe/Samara')
```
Даже на сайте МТТ (https://www.mtt.ru/pomosh-i-podderzhka/defcodes/) можно узнать что это диапазон Оренбургской области.

**Comment by spider863644** [comment]
English

**Comment by krotesk** [comment]
Inaccurately defines the time zone
Across Russia to help http://opendata.digital.gov.ru/registry/numeric/downloads (Выписка по диапазону 9xx) - That error also applies to

**Comment by spider863644** [comment]
Ok
I'll fix it
