### ISSUE TITLE
Не распознает перенесенные номера

### ISSUE THREAD

**Issue by krotesk** [spider863644/PhoneNumber-OSINT#2]
```
Enter phone number with country code: +792262.....
The Internet Service Provider(ISP)  is :  MegaFon
```
Номер уже лет 7 как перенесен с Мегафона в Теле2

**Comment by spider863644** [comment]
English pls

**Comment by krotesk** [comment]
Does not recognize transferred numbers
The number has been transferred from Megaphone to Tele2 for 7 years now

**Comment by spider863644** [comment]
+2349052863644
Private Chat me on WhatsApp

**Comment by spider863644** [comment]
Ok
