### ISSUE TITLE
requirements missing?

### ISSUE THREAD

**Issue by Wicked816** [spider863644/PhoneNumber-OSINT#5]
I ran the pip install -r requirements.txt. it did all of the installing and i got the message that "Some requirements are missng"
I ran the install command again and it says that everything is already installed. 
Tried the "python3 phonenumber_osint.py and same message:
Some requirements are missing!
Run "pip install -r requirements.txt" then run :python3 phonenumber_osint.py"

Any ideas?

**Comment by spider863644** [comment]
Try installing the requirements manually

Open terminal and type
pip install Colorado

pip install phonenumber
